# Nuxtのビルド、Firebaseへのデプロイ、Slack通知

name: Build and deploy to Firebase, Notify Slack

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm install
          npm run generate
      - name: Firebase-tools install
        run: npm install -g firebase-tools
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # ビルド成功時にSlack通知を飛ばす
      - name: post message to Slack
        if: success()
        uses: tokorom/action-slack-incoming-webhook@master
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "GitHub Actions成功!!"
#          blocks: |
#            [
#              {
#                "type": "section",
#                "text": {
#                  "type": "mrkdwn",
#                  "text": "デプロイ完了しました!! :clap:"
#                }
#              },
#              {
#                "type": "divider"
#              },
#              {
#                "type": "section",
#                "text": {
#                  "type": "mrkdwn",
#                  "text": "*${{ github.event.pull_request.title }}*\nPushed by ${{ github.event.pull_request.user.login }}\n\n*URL*\n${{ github.event.pull_request.url }}"
#                },
#                "accessory": {
#                  "type": "image",
#                  "image_url": "${{ github.event.pull_request.user.avatar_url }}",
#                  "alt_text": "User Icon"
#                }
#              },
#              {
#                "type": "actions",
#                  "elements": [
#                    {
#                      "type": "button",
#                      "text": {
#                        "type": "plain_text",
#                        "text": "アプリを開く"
#                      },
#                      "url": "${{ secrets.APP_URL }}"
#                    }
#                  ]
#                },
#                {
#                  "type": "divider"
#                }
#              ]
