# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set Git Config
        run: |
          git config --global user.name "Nuxt Firebase CD"
          git config --global user.email git@qst.com
      - name: Patch release
        # コミットメッセージに特に指定がない場合はマイナーバージョンを更新する
        id: patch
        run: |
          git fetch
          git status
          exists_patch=`git log --oneline origin/main..HEAD | grep 'bump up version' | wc -l`
          echo $exists_patch
          if [ $exists_patch = 0 ]; then
            npm version patch -m "bump up version patch: %s"
          fi
          git push origin ${GITHUB_REF}
